resolver: lts-17.14
packages:
- .
extra-deps:
- HSH-2.1.3
- monoidal-containers-0.6.0.1
- restless-git-0.7
- s-cargot-0.1.4.0
- tree-view-0.5
- text-format-0.3.2
- witherable-0.3.5
- base16-bytestring-1.0.1.0@sha256:33b9d57afa334d06485033e930c6b13fc760baf88fd8f715ae2f9a4b46e19a54,2641
- github: dmjio/semver-range
  commit: d8d9db892ddb6ae267c9bcbc4f6602668433f12a
- github: leventerkok/sbv # 8.9
  commit: b64905e2698c320ac14ffbad53325d33081839fb
flags: {}
extra-package-dbs: []
image:
  container:
    name: mbrock/hevm
    base: haskell:8.0.1
