#!/usr/bin/env bash
### seth---to-uint128 -- convert an integer into uint16 value
### Usage: seth --to-uint128 <value>
set -e
[[ $1 ]] || set -- "$(cat)"
hex=$(seth --to-hex "$1")
printf "0x%32s\\n" "${hex#0x}" | tr ' ' 0
