#!/usr/bin/env bash
### seth-etherscan-source -- fetch the contract source from etherscan
### Usage: seth etherscan-source <address> [<options>]
###
### Requires an etherscan api key assigned to ETHERSCAN_API_KEY
set -e

if [ "$SETH_VERBOSE" ]; then set -x; fi

[[ $ETHERSCAN_API_KEY ]] || {
  cat >&2 <<.

  You need an Etherscan Api Key to source contracts.
  Create one at https://etherscan.io/myapikey

  Then export it with \`export ETHERSCAN_API_KEY=xxxxxxxx'

.
  exit 1
}

[[ -z "$1" ]] && seth --fail-usage

ADDR=$(seth --to-address "$1")

chain=$(seth chain)

case "$chain" in
  ethlive|mainnet)
    URL="${ETHERSCAN_API_URL:+https://api.etherscan.io/api}"
    ;;
  goerli)
    URL="${ETHERSCAN_API_URL:+https://api-$chain.etherscan.io/api}"
    ;;
  optimism-mainnet)
    URL="${ETHERSCAN_API_URL:-https://api-optimistic.etherscan.io}"
    ;;
  arbitrum-mainnet)
    URL="${ETHERSCAN_API_URL:-https://api.arbiscan.io}"
    ;;
  bsctest)
    URL="${ETHERSCAN_API_URL:-https://api-testnet.bscscan.com/api}"
    ;;
  bsc)
    URL="${ETHERSCAN_API_URL:-https://api.bscscan.com/api}"
    ;;
  hecotest)
    URL="${ETHERSCAN_API_URL:-https://http-testnet.hecochain.com/api}"
    ;;
  heco)
    URL="${ETHERSCAN_API_URL:-https://http-mainnet-node.huobichain.com/api}"
    ;;
  polygon)
    URL="${ETHERSCAN_API_URL:-https://api.polygonscan.com}"
    ;;
  mumbai)
    URL="${ETHERSCAN_API_URL:-https://api-testnet.polygonscan.com}"
    ;;
  fantom)
    URL="${ETHERSCAN_API_URL:-https://api.ftmscan.com}"
    ;;
  *)
    echo >&2 "Source fetching only works on mainnet, goerli, optimism-mainnet, arbitrum-mainnet, polygon, and fantom."
    exit 1
esac


RESPONSE=$(seth curl "${URL}?module=contract&action=getsourcecode&address=${ADDR}&apikey=${ETHERSCAN_API_KEY}" | seth --show-json)

MSG=$(echo "$RESPONSE" | seth --field message)

ABI=$(echo "$RESPONSE" | seth --field result | jq '.[0].ABI' | seth --show-json)

[[ $MSG == OK ]] || seth --fail "error: bad response: $MSG"


if [[ $ABI == "Contract source code not verified" ]]; then
    seth --fail "$ABI"
else
    echo "$RESPONSE" | seth --field result | jq '.[0]'
fi
